# Generated by Django 3.2.7 on 2021-10-04 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.DeleteModel(
            name='EmpresaConvenio',
        ),
        migrations.DeleteModel(
            name='TipoCliente',
        ),
    ]
