# Generated by Django 3.2.7 on 2021-10-04 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20211004_0812'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpresaConvenio',
            fields=[
                ('rutempresaconvenio', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('razonsocial', models.CharField(max_length=30)),
                ('fechaconvenio', models.DateField()),
            ],
            options={
                'db_table': 'empresa_convenio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoCliente',
            fields=[
                ('idtipocliente', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'tipo_cliente',
                'managed': False,
            },
        ),
    ]
